### ISSUE TITLE
📌 2. Yo como usuaria quiero tomar nota para no depender de mi mala memoria y tener presente en todo momento los apuntes ó cosas importantes que antes escribía en papel.

### ISSUE THREAD

**Issue by roxypoceros** [roxypoceros/CDMX012-notes#2]
**Criterios de aceptación**
- [ ] Debería poder tomar nota y guardarla.

**Definición de terminado**
- [ ] Recibí code review de una compañera.
- [ ] Hice test unitarios y he testeado el producto manualmente.
- [ ] Desplegué la aplicación.
- [ ] Etiqueté la versión (git tag).
